### ISSUE TITLE
Axe and Chrome return "undefined"

### ISSUE THREAD

**Issue by ferllings** [paypal/AATT#21]
I tested on Mac and Debian. Did I forgot to setup anything?

```
  AATT:log  +9s
  AATT:log E N G I N E  axe +6s
  AATT:log undefined
  AATT:log  +754ms
  AATT:log E N G I N E  axe +39m
  AATT:log undefined
  AATT:log  +783ms
  AATT:log E N G I N E  axe +30m
  AATT:log undefined
  AATT:log  +716ms
```

**Comment by mpnkhan** [comment]
Did you use the web interface or the API?

**Comment by ferllings** [comment]
Yes via the web interface.
A fresh install, with the latest versions.

I need to mention that Axe and Chrome are working with the Test HTML panel.
But not with URLs

**Comment by horfic** [comment]
we got the same issue

**Comment by mpnkhan** [comment]
URL were broken with the update of engines. Fixed with this commit https://github.com/paypal/AATT/commit/36c7f901244a56e929159086ad547ad11420e774. 
Also have added a local version which doesn't use phantomJS localhost/test/index.html should work.
 could you try accessing localhost/test/index.html and post the results?

**Comment by ferllings** [comment]
That works for me
